# Generated by Django 3.0.2 on 2020-01-26 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_item_depth_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='depth_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Уровень'),
        ),
    ]
